coverage:
  status:
    project:
      default:
        informational: true
        threshold: 0%
        base: auto
    patch:
      default:
        informational: true
        

ignore:
  - src/test/
  - src/uiTest/
